# Generated by Django 5.0.7 on 2024-07-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="arcticule",
            field=models.CharField(
                default=None, max_length=255, unique=True, verbose_name="Артикул"
            ),
            preserve_default=False,
        ),
    ]
